name: Test
on: [push]

jobs:
  test:
    name: Test Rust, WASM, JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install node deps
        run: npm i

      - name: Cache rust crates
        uses: actions/cache@v1
        env:
          cache-name: cache-rust-crates
        with:
          path: ~/.cargo/registry/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust deps
        run: cargo build

      - name: Test Rust
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Test wasm-bindgen
        run: npx wasm-pack test --node
      - name: Test WASM, JS
        run: make build && npm t
