name: Test
on: [push]

jobs:
  test:
    name: Test Rust, WASM, JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Test Rust
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Test wasm-bindgen
        run: wasm-pack test --node
      - name: Test WASM, JS
        run: wasm-pack build --scope xoperations --target nodejs --out-name index && npm i && npm t
